# Generated by Django 4.1.5 on 2023-01-29 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_project_category_projectimages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='goal',
            field=models.FloatField(),
        ),
        migrations.DeleteModel(
            name='ProjectImages',
        ),
    ]
