# Generated by Django 4.1.5 on 2023-01-16 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_category_alter_pledge_amount_project_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('Health', 'Health'), ('Disaster Relief', 'Disaster Releif'), ('Education', 'Education')], max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
