# Generated by Django 4.1.5 on 2023-02-23 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_alter_pledge_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='total_raised',
            field=models.FloatField(null=True),
        ),
    ]
